version: "2"

services:

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=encontra_ja
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"

  backend_api:
    image: ambientum/php:7.1-caddy
    volumes:
      - .:/var/www/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=encontra_ja
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - MAIL_DRIVER=mailgun
      - MAILGUN_DOMAIN=mg.encontraja.com.br
      - MAILGUN_SECRET=key-e4546832bd7da8cf91b161eb69d9d4cb
      - MAIL_FROM_ADDRESS=suporte@mg.encontraja.com.br
      - APP_NAME=EncontraJa_Backend_API
      - APP_ENV=development
      - APP_DEBUG=false

    ports:
      - "8799:8080"
    links:
      - db
    tty: true
